### ISSUE TITLE
Packagist reports bug in one or more composer files.

### ISSUE THREAD

**Issue by forikal-uk** [xmlsquad/xml-authoring-project#2]
I received an email from packagist:

It is saying:

> The forikal-uk/xml-authoring-project package of which you are a maintainer has
> failed to update due to invalid data contained in your composer.json.
> Please address this as soon as possible since the package stopped updating.
> 
> It is recommended that you use `composer validate` to check for errors when you
> change your composer.json.
> 
> Below is the full update log which should highlight errors as
> "Skipped branch ...":
> 
> [Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches
> 
> Skipped parsing master, "master:composer.json" does not contain valid JSON
> Parse error on line 55:
> ...nd": "^0.2"        "forikal-uk/ping-dri...
> ---------------------^
> Expected one of: 'EOF', '}', ':', ',', ']'
> Reading composer.json of https://github.com/forikal-uk/xml-authoring-project (v0.2.1)
> Skipped tag v0.2.1, "4a3490bd41b998fd663442828ed525b311a395b1:composer.json" does not contain valid JSON
> Parse error on line 55:
> ...nd": "^0.2"        "forikal-uk/ping-dri...
> ---------------------^
> Expected one of: 'EOF', '}', ':', ',', ']'
> Reading composer.json of https://github.com/forikal-uk/xml-authoring-project (v0.2.0)
> Skipped tag v0.2.0, "aa5b75ff2c55255a7656080da9261f299d5b7a98:composer.json" does not contain valid JSON
> Parse error on line 55:
> ...nd": "^0.2"        "forikal-uk/ping-dri...
> ---------------------^
> Expected one of: 'EOF', '}', ':', ',', ']'
> Reading composer.json of https://github.com/forikal-uk/xml-authoring-project (v0.0.1)
> Importing tag v0.0.1 (0.0.1.0)
> Reading composer.json of https://github.com/forikal-uk/xml-authoring-project (changes)
> Importing branch changes (dev-changes)
> Reading composer.json of https://github.com/forikal-uk/xml-authoring-project (master)
> Skipped branch master, "20cb841b0b4aa3a4024a90f625dd03f00fe17f71:composer.json" does not contain valid JSON
> Parse error on line 55:
> ...nd": "^0.2"        "forikal-uk/ping-dri...
> ---------------------^
> Expected one of: 'EOF', '}', ':', ',', ']'
> 
> 
>

**Comment by forikal-uk** [comment]
I fixed the composer.json in master and tagged a new later release and then went to  github > project settings > integrations > packagist > test

So I shall await any reports via email to let me know how I did.

**Comment by forikal-uk** [comment]
I did that previous fix by editing the file directly on Github. After doing so I realised I was being sloppy. So, decided to clone the repo and run `composer validate` on the `composer.json`, like a good boy should.

This is what I got:

```bash
$ pwd
/Users/x/Documents/Projects/XmlAuthoring/xml-authoring-project

$ composer validate
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
The property repositories-local is not defined and the definition does not allow additional properties
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`.
```

So, let's do that...

```bash
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                               
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package forikal-uk/xml-authoring-tools ^0.2 exists as forikal-uk/xml-authoring-tools[dev-feature-helloworld, dev-master, v0.0.1, v0.0.2, v0.0.3, v0.1.0, v0.1.1] but these are rejected by your constraint.
  Problem 2
    - The requested package forikal-uk/xmlauthor-example-command ^0.2 exists as forikal-uk/xmlauthor-example-command[dev-master] but these are rejected by your constraint.
  Problem 3
    - The requested package forikal-uk/gsheet-to-xml could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

**Comment by forikal-uk** [comment]
So, there are 3 issues.

With Problem 3 I had created an inconsistency when I named that package. 

I have chatted with @zota123 on Skype and we will rename the package from 

`forikal/gsheet-to-xml` 

to 

`forikal-uk/gsheet-to-xml `

and then I will submit that as a new Package on packagist.

**Comment by igormukhingmailcom** [comment]
Hi.
Sorry, some of errors was because I've pushed changes without tags to github.
Now only one error still there - with https://github.com/forikal-uk/gsheet-to-xml as far as it haven't any tags (and I have no rights to assign tag).

Could someone please tag `gsheet-to-xml` it as `v0.2.0`?

**Comment by forikal-uk** [comment]
Thanks @igormukhingmailcom -  Yes. I can do that now.

**Comment by forikal-uk** [comment]
I think it is sorted now.

```bash
$ pwd 
/Users/x/Documents/Projects/XmlAuthoring/gsheet-to-xml
$ composer validate
./composer.json is valid
$ git tag -a v0.2.0 -m "See https://github.com/forikal-uk/xml-authoring-project/issues/2#issuecomment-394124253"
$ git tag
v0.2.0
$ git push origin v0.2.0
Counting objects: 1, done.
Writing objects: 100% (1/1), 269 bytes | 269.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To github.com:forikal-uk/gsheet-to-xml.git
 * [new tag]         v0.2.0 -> v0.2.0

```

**Comment by john-arcus** [comment]
I did a `composer update` in xml-authoring-project and there is a missing link in the bin statement of gsheet-to-xml



```bash
$ pwd
/Users/x/Documents/Projects/XmlAuthoring/xml-authoring-project
$ composer validate
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
The property repositories-local is not defined and the definition does not allow additional properties
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`.
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                               
Package operations: 22 installs, 1 update, 0 removals
  - Installing psr/log (1.0.2): Downloading (100%)         
  ...
google/apiclient suggests installing cache/filesystem-adapter (For caching certs and tokens (using Google_Client::setCache))
Writing lock file
Generating autoload files
    Skipped installation of bin bin/gsheetxml for package forikal-uk/gsheet-to-xml: file not found in package

```

The gsheet-to-xml [composer.json](https://github.com/forikal-uk/gsheet-to-xml/blob/master/composer.json) has a line:

```json
{
  "name": "forikal-uk/gsheet-to-xml",
 ...
  },
...
  "bin": [
    "bin/gsheetxml"
  ]
}
```

I was going to fix this. But I will leave it to someone with more knowledge.

**Comment by john-arcus** [comment]
Actually I will fix this now.

**Comment by john-arcus** [comment]
I have done that.

Still getting some kind of error in the composer validate for project.

```bash
$ pwd
/Users/x/Documents/Projects/XmlAuthoring/xml-authoring-project
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                               
Package operations: 0 installs, 1 update, 0 removals
  - Updating forikal-uk/gsheet-to-xml (v0.2.0 => v0.2.1): Downloading (100%)         
Writing lock file
Generating autoload files
$ composer validate
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
The property repositories-local is not defined and the definition does not allow additional properties
```

I will leave that to someone who knows about repositories-local.

**Comment by igormukhingmailcom** [comment]
Hi, @john-arcus 
`repositories-local` is undefined in composer's specs option - its just workaround to fast ability to use local repositories in development. Developer should rename option `repositories-local` to defined `repositories` to force composer to get information from local repositories rather than from packagist database.

So I would suggest to leave that option in our composer.json - it just helping developers. From other side - all things working even with this undefined option and it just print next line:

```
The property repositories-local is not defined and the definition does not allow additional properties
```

If we can just ignore that message - lets leave `repositories-local` as is.

**Comment by john-arcus** [comment]
Thanks @igormukhingmailcom .

I am still a bit confused. 

If the `repositories-local` is not defined by [composer](https://getcomposer.org/doc/04-schema.md), how does composer know how to use the property?

Is it an undocumented feature?

Is this just a hack to add a comment to a json file?

Is this a common practice or just some technique in this current project?
Can you point me to more information about the usage of `repositories-local`.

**Comment by igormukhingmailcom** [comment]
Yes, this is a hack - this way composer ignore "repositories" section (as far as it renamed to "repositories-local"). 

The developer, when he wants to check some changes - renames "repositories-local" to "repositories" and since then he can check repositories consistency as far as composer will use our local repositories to update/install.

As far as we can't add any comments in `composer.json` file - this is the only one way how to put some code that should be ignored, but very useful to be present on our `composer.json`.

Just ignore that warning at `composer validate`.

**Comment by john-arcus** [comment]
Aaah. I get it now.

Thanks for taking the time to explain. I feel uncomfortable seeing an error notice on the validation output. But, I suppose I can live with it. :)

So, yes we can leave it. [I have  documented it on the project so that others understand it](https://github.com/forikal-uk/xml-authoring-project/blob/master/README.md#development-notes).
